export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Signup } from './Signup'
export { default as Game } from './Game'
export { default as History } from './History'
export { default as Log } from './Log'